FROM python:3.8.1-slim

RUN apt-get update
RUN apt-get install -y software-properties-common

RUN apt-get install -y \
    python3-pip python3-dev python3-setuptools \
    --no-install-recommends

RUN apt-get update && apt-get install gettext nano vim -y
RUN pip3 install --upgrade pip
# RUN pip install --upgrade pip

RUN apt-get install ffmpeg libsm6 libxext6  -y
RUN apt-get install -y cron

WORKDIR /src
COPY . /src

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# RUN apt-get install apt-utils
# RUN apt-get install cmake -y

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt
RUN apt install tesseract-ocr-tha -y

RUN echo "Asia/Bangkok" > /etc/timezone && rm /etc/localtime && dpkg-reconfigure -f noninteractive tzdata

EXPOSE 5000

# CMD ["python3", "-m" , "flask", "run", "--host=0.0.0.0"]
CMD ["python", "app.py"]
