name: Build and deploy a container to an Azure Web App

env:
  AZURE_WEBAPP_NAME: vekin-ocr-ml-prod # set this to the name of your Azure Web App
  SLOT_NAME: staging

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ secrets.ACR_URL_PROD }}
          username: ${{ secrets.ACR_USERNAME_PROD }}
          password: ${{ secrets.ACR_PASSWORD_PROD }}

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.ACR_URL_PROD }}/${{ env.REPO }}:${{ github.sha }}
          file: deployment/Dockerfile.prod

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "prod"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_STAGING }}
          images: ${{ secrets.ACR_URL_PROD }}/${{ env.REPO }}:${{ github.sha }}
          slot-name: ${{ env.SLOT_NAME }}
